#!/usr/bin/env python3
"""
ARGOS Dashboard Generator — генерирует Obsidian страницу с живыми данными.
"""
import sys, os, time, json, urllib.request
from datetime import datetime
from pathlib import Path

sys.path.insert(0, '/home/ava/Projects/argoss/src/audit')
sys.path.insert(0, '/home/ava/Projects/argoss/scripts')

OUT = Path('/home/ava/Documents/MyObsidianVault/SharedMemory/entities/ARGOS_DASHBOARD.md')


def get_text(url, timeout=5):
    """GET URL и вернуть text content."""
    try:
        with urllib.request.urlopen(url, timeout=timeout) as r:
            return r.status, r.read().decode()
    except Exception as e:
        return 0, str(e)


def get_json(url, timeout=5):
    """GET URL и вернуть parsed JSON."""
    code, text = get_text(url, timeout)
    try:
        return code, json.loads(text)
    except Exception:
        return code, {"raw": text[:500]}


def main():
    # Prometheus /metrics (plain text format)
    code, metrics_text = get_text("http://localhost:19090/metrics")
    metric_dict = {}
    if code == 200:
        for line in metrics_text.split("\n"):
            if line and not line.startswith("#"):
                parts = line.split()
                if len(parts) >= 2:
                    try:
                        metric_dict[parts[0]] = float(parts[1])
                    except ValueError:
                        pass
    # Trust
    code, trust = get_json("http://localhost:5010/trust")
    trust_dict = {n["node_id"]: n for n in trust} if code == 200 and isinstance(trust, list) else {}
    # Alerts
    code, alerts = get_json("http://localhost:5010/alerts?min_severity=INFO")
    # Brain (using PC Brain as primary)
    code, brain = get_json(os.getenv("ARGOS_BRAIN_API_URL", "http://192.168.1.53:5001/brain/nodes"))

    def status_for(conf):
        if conf > 0.7: return "✅ OK"
        if conf > 0.3: return "⚠️ LOW"
        return "🔴 BLOCKED"

    def get_trust(node):
        return trust_dict.get(node, {}).get("confidence", 1.0)

    now = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    md = f"""# 🛡️ ARGOS Real-Time Dashboard

_Last update: {now}_

## 🖥️ System
| Metric | Value |
|--------|-------|
| CPU | {metric_dict.get('argos_cpu_percent', 0):.1f}% |
| RAM | {metric_dict.get('argos_ram_percent', 0):.1f}% |
| Disk | {metric_dict.get('argos_disk_percent', 0):.1f}% |
| Brain API | {'🟢 UP' if metric_dict.get('argos_brain_api_up') else '🔴 DOWN'} |
| Nodes online | {int(metric_dict.get('argos_nodes_online', 0))}/{int(metric_dict.get('argos_nodes_total', 0))} |
| Entity cycles | {int(metric_dict.get('argos_entity_cycles_total', 0))} |
| Thoughts | {int(metric_dict.get('argos_thoughts_total', 0))} |
| Syntheses | {int(metric_dict.get('argos_syntheses_total', 0))} |
| Evolutions | {int(metric_dict.get('argos_evolutions_total', 0))} |
| KG | {int(metric_dict.get('argos_kg_nodes', 0))} nodes / {int(metric_dict.get('argos_kg_edges', 0))} edges |

## 🔒 Trust Scores (VetoProtocol)
| Node | Confidence | Status |
|------|-----------|--------|
| orion | {get_trust('orion'):.2f} | {status_for(get_trust('orion'))} |
| nexus | {get_trust('nexus'):.2f} | {status_for(get_trust('nexus'))} |
| egida | {get_trust('egida'):.2f} | {status_for(get_trust('egida'))} |
| pico | {get_trust('pico'):.2f} | {status_for(get_trust('pico'))} |
| esp32 | {get_trust('esp32'):.2f} | {status_for(get_trust('esp32'))} |
| android | {get_trust('android'):.2f} | {status_for(get_trust('android'))} |
| phone-redmi | {get_trust('phone-redmi'):.2f} | {status_for(get_trust('phone-redmi'))} |

## 🚨 Active Alerts ({len(alerts) if isinstance(alerts, list) else 0})
"""
    if isinstance(alerts, list) and alerts:
        md += "| Severity | Name | Message |\n|----------|------|---------|\n"
        for a in alerts[:10]:
            md += f"| {a.get('severity', '?')} | {a.get('name', '?')} | {a.get('message', '?')[:80]} |\n"
    else:
        md += "✅ No active alerts\n"

    md += f"""
## 📊 Audit Log
- Total events: {int(metric_dict.get('argos_audit_events_total', 0))}
- Chain verified: {'✅' if metric_dict.get('argos_audit_chain_verified') else '❌'}

## 🔗 Live Endpoints
- Dashboard: http://localhost:19090/dashboard
- Metrics: http://localhost:19090/metrics
- Trust API: http://localhost:5010/trust
- Brain API: http://192.168.1.53:5001/brain/nodes (PC Master)
- Audit Proxy: http://localhost:5002/trust

---
_Generated by ARGOS v2.1.4 · {now}_
_Autorefresh: every 60s_
"""

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(md, encoding='utf-8')
    print(f"✓ Dashboard updated: {OUT}")
    print(f"  Trust orion: {get_trust('orion'):.2f}")
    print(f"  Alerts: {len(alerts) if isinstance(alerts, list) else 0}")


if __name__ == "__main__":
    main()
