#!/bin/bash
# ARGOS All Dongles + ESPs Auto-Configuration
# Run on: Orange Pi (root) or any ARGOS node
# What it does:
#   1. Detects Zigbee USB coordinator
#   2. Detects ESP USB devices (CH340/CP210x)
#   3. Configures Zigbee2MQTT
#   4. Configures ESPHome (if docker/venv available)
#   5. Restarts all services

set -euo pipefail

NODE="orangepi"
LOG="/var/log/argos_dongles_setup.log"
Z2M_DIR="/opt/zigbee2mqtt"
ESPHOME_DIR="/root/esphome_configs"

timestamp() { date '+%Y-%m-%d %H:%M:%S'; }
log() { echo "$(timestamp) $*" | tee -a "$LOG"; }

mkdir -p "$Z2M_DIR" "$ESPHOME_DIR"

# =====================
# 1. USB DEVICE DETECTION
# =====================
log "=== USB Device Scan ==="

ZIGBEE_PORT=""
ESP_PORTS=()

# Scan USB serial devices
for dev in /dev/ttyUSB* /dev/ttyACM*; do
    [ -e "$dev" ] || continue
    log "Found serial: $dev"
    
    # Try to identify via udev or product strings
    DEVNAME=$(basename "$dev")
    UDEV_INFO=$(udevadm info -q property -n "$dev" 2>/dev/null || true)
    
    if echo "$UDEV_INFO" | grep -qi -E 'cc253|cc265|zigbee|silabs|conbee|sonoff.*zb|slzb'; then
        ZIGBEE_PORT="$dev"
        log "  -> Identified as ZIGBEE coordinator: $dev"
    elif echo "$UDEV_INFO" | grep -qi -E 'ch340|cp210|ftdi|esp32|esp8266'; then
        ESP_PORTS+=("$dev")
        log "  -> Identified as ESP bridge: $dev"
    else
        # Fallback: check with lsusb path
        BUSDEV=$(udevadm info -q property -n "$dev" 2>/dev/null | grep DEVPATH | head -1)
        log "  -> Unknown device (udev: $BUSDEV)"
    fi
done

# Also check lsusb for IDs
LSUSB=$(lsusb 2>/dev/null || true)
log "lsusb output:"
echo "$LSUSB" | while read line; do log "  $line"; done

# =====================
# 2. ZIGBEE2MQTT CONFIG
# =====================
if [ -n "$ZIGBEE_PORT" ]; then
    log "=== Configuring Zigbee2MQTT ==="
    log "Coordinator port: $ZIGBEE_PORT"
    
    # Detect adapter type from chip
    ADAPTER="zstack"  # default for CC2652/CC2538
    if echo "$LSUSB" | grep -qi "conbee"; then ADAPTER="deconz"; fi
    if echo "$LSUSB" | grep -qi "sonoff.*zb.*e"; then ADAPTER="ezsp"; fi
    
    cat > "$Z2M_DIR/data/configuration.yaml" <<Z2MCFG
# Zigbee2MQTT config — Auto-generated by ARGOS
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.53:1883
  user: argos
  password: argos_mqtt_pass
serial:
  port: $ZIGBEE_PORT
  adapter: $ADAPTER
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key: GENERATE
frontend:
  port: 8099
  host: 0.0.0.0
devices: devices.yaml
groups: groups.yaml
Z2MCFG
    
    # Create data dir and empty device files
    mkdir -p "$Z2M_DIR/data"
    touch "$Z2M_DIR/data/devices.yaml"
    touch "$Z2M_DIR/data/groups.yaml"
    
    # Fix permissions for node user
    if id zigbee2mqtt &>/dev/null; then
        chown -R zigbee2mqtt:zigbee2mqtt "$Z2M_DIR/data"
    fi
    
    # Restart Z2M (if systemd service exists)
    if systemctl list-unit-files | grep -q zigbee2mqtt; then
        systemctl restart zigbee2mqtt || log "Z2M restart via systemctl failed"
    elif [ -f /etc/init.d/zigbee2mqtt ]; then
        /etc/init.d/zigbee2mqtt restart || log "Z2M restart via init.d failed"
    else
        log "No Z2M service found. Start manually: cd $Z2M_DIR && npm start"
    fi
    
    log "Z2M config written to $Z2M_DIR/data/configuration.yaml"
else
    log "WARNING: No Zigbee USB coordinator detected!"
    log "  Please check: lsusb, dmesg | tail -20"
fi

# =====================
# 3. ESPHOME CONFIGS
# =====================
log "=== Configuring ESPHome ==="

# ESP #1 — ESP8266 Bridge (existing, already flashed via previous sessions)
# ESP #2 — ESP32 Display (existing, already flashed)
# New ESPs connected via USB for flashing

ESP_COUNT=${#ESP_PORTS[@]}
log "Detected $ESP_COUNT ESP USB devices"

if [ "$ESP_COUNT" -gt 0 ]; then
    # Check if esphome CLI available
    if command -v esphome &>/dev/null; then
        log "ESPhome CLI found"
    elif [ -f /usr/local/bin/esphome ]; then
        log "ESPhome found at /usr/local/bin/esphome"
    else
        log "WARNING: esphome CLI not found. Install: pip install esphome"
    fi
    
    # Config for generic ESP8266 (new USB-connected device)
    cat > "$ESPHOME_DIR/esp-usb-sensor.yaml" <<ESPCFG
esphome:
  name: argos-esp-usb-sensor
  friendly_name: ARGOS USB Sensor

esp8266:
  board: d1_mini

# WiFi — will be configured via captive portal or API
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "ARGOS-USB-Fallback"
    password: "argos12345"

captive_portal:

# API for Home Assistant
api:
  encryption:
    key: !secret api_encryption_key

# MQTT to laptop broker
mqtt:
  broker: 192.168.1.53
  username: argos
  password: argos_mqtt_pass
  topic_prefix: argos/esp/usb-sensor

# I2C for sensors
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true

# Common sensors
sensor:
  - platform: dht
    pin: GPIO14
    temperature:
      name: "USB Sensor Temperature"
    humidity:
      name: "USB Sensor Humidity"
    update_interval: 60s
  - platform: wifi_signal
    name: "USB Sensor WiFi Signal"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: GPIO12
    name: "USB Sensor Motion"
    device_class: motion

status_led:
  pin: GPIO2
ESPCFG

    # Config for generic ESP32 (second USB device)
    cat > "$ESPHOME_DIR/esp32-usb-actuator.yaml" <<ESPCFG2
esphome:
  name: argos-esp32-usb-actuator
  friendly_name: ARGOS USB Actuator

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "ARGOS-ACTUATOR-Fallback"
    password: "argos12345"

captive_portal:

api:
  encryption:
    key: !secret api_encryption_key

mqtt:
  broker: 192.168.1.53
  username: argos
  password: argos_mqtt_pass
  topic_prefix: argos/esp/usb-actuator

# Relay output
switch:
  - platform: gpio
    pin: GPIO25
    name: "USB Actuator Relay 1"
    id: relay1
  - platform: gpio
    pin: GPIO26
    name: "USB Actuator Relay 2"
    id: relay2

# ADC input
sensor:
  - platform: adc
    pin: GPIO34
    name: "USB Actuator ADC"
    update_interval: 5s
    attenuation: auto

status_led:
  pin:
    number: GPIO2
    inverted: true
ESPCFG2

    log "ESPHome configs written:"
    log "  $ESPHOME_DIR/esp-usb-sensor.yaml (ESP8266)"
    log "  $ESPHOME_DIR/esp32-usb-actuator.yaml (ESP32)"
    
    # Secrets template
    if [ ! -f "$ESPHOME_DIR/secrets.yaml" ]; then
        cat > "$ESPHOME_DIR/secrets.yaml" <<SECRETS
# ESPHome secrets — generated by ARGOS
# EDIT THESE!
wifi_ssid: "SiG"
wifi_password: "your-wifi-password"
api_encryption_key: "$(openssl rand -base64 32)"
SECRETS
        log "  $ESPHOME_DIR/secrets.yaml (generated, PLEASE EDIT)"
    fi
else
    log "No ESP USB devices detected."
fi

# =====================
# 4. ORANGE PI UART BRIDGE
# =====================
log "=== UART Bridge Setup ==="

# Enable UART overlays if needed
if [ -f /boot/armbianEnv.txt ]; then
    if ! grep -q "overlays=.*uart" /boot/armbianEnv.txt; then
        log "Adding uart overlays to armbianEnv.txt"
        sed -i 's/^overlays=/overlays=uart1 uart2 uart3 /' /boot/armbianEnv.txt 2>/dev/null || \
            echo "overlays=uart1 uart2 uart3" >> /boot/armbianEnv.txt
        log "UART overlays added. REBOOT REQUIRED for ttyS1-S3 activation."
    fi
fi

# =====================
# 5. SUMMARY & STATUS
# =====================
log ""
log "======================================"
log "ARGOS Dongle/ESP Setup Complete"
log "======================================"
log "Zigbee Port:   ${ZIGBEE_PORT:-NOT FOUND}"
log "ESP Ports:     ${ESP_PORTS[*]:-none}"
log "ESP Count:     $ESP_COUNT"
log "Z2M Config:    $Z2M_DIR/data/configuration.yaml"
log "ESPHome Dir:   $ESPHOME_DIR"
log ""
log "Next steps:"
[ -n "$ZIGBEE_PORT" ] && log "  - Z2M: cd $Z2M_DIR && npm start"
[ "$ESP_COUNT" -gt 0 ] && log "  - ESPHome: esphome run $ESPHOME_DIR/esp-usb-sensor.yaml"
log "  - If Zigbee not detected, check: lsusb, dmesg | grep -i tty"
log "  - After changing armbianEnv.txt: reboot"
