#!/usr/bin/env python3
"""
ARGOS Entity Task Runner — сущности как субъекты с реальными задачами.
Каждая сущность берёт задачу из очереди и ВЫПОЛНЯЕТ её с реальными инструментами.
"""
import os, sys, json, time, subprocess, shutil, re, urllib.request
from pathlib import Path
from datetime import datetime

VAULT = Path("/home/ava/Documents/MyObsidianVault/SharedMemory")
ARGOS = Path("/home/ava/Projects/argoss")
TOKENS = json.load(open(ARGOS / "data/entity_bot_tokens.json"))
GROUP_ID = -5129226282
INTERVAL = 60  # каждые 60 сек новая задача

def get_env(key):
    c = open(ARGOS / ".env").read()
    m = re.search(f"{key}=([^\\n\\s]+)", c)
    return m.group(1).strip() if m else ""

def send_to_group(bot_name: str, message: str):
    token = TOKENS.get(bot_name, "")
    if not token: return
    body = json.dumps({"chat_id": GROUP_ID, "text": message[:4000]}).encode()
    req = urllib.request.Request(f"https://api.telegram.org/bot{token}/sendMessage",
        data=body, headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=8) as r:
            d = json.load(r)
            return d['result']['message_id']
    except: return None

def write_obsidian(path: str, content: str):
    p = VAULT / path
    p.parent.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    existing = p.read_text(errors="replace") if p.exists() else f"# {p.name}\n"
    tmp = p.parent / f"_tmp_{p.name}"
    tmp.write_text(existing + f"\n## [{ts}]\n{content}\n")
    shutil.move(str(tmp), str(p))

def run_cmd(cmd: str, timeout=10) -> str:
    try:
        r = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=timeout, errors="replace")
        return (r.stdout + r.stderr)[:500]
    except Exception as e:
        return str(e)[:100]

def brain_api(path="/brain/nodes"):
    try:
        r = urllib.request.urlopen(f"http://192.168.1.53:5001{path}", timeout=5)
        return json.loads(r.read())
    except: return {}

def ha_api(path="/api/states"):
    try:
        tok = get_env("HA_TOKEN")
        req = urllib.request.Request(f"http://localhost:8123{path}",
            headers={"Authorization": f"Bearer {tok}"})
        with urllib.request.urlopen(req, timeout=5) as r:
            return json.load(r)
    except: return []

# ── ЗАДАЧИ СУЩНОСТЕЙ ──────────────────────────────────────────────────

def claude_task():
    """Клод: пишет реальный код для ARGOS и деплоит."""
    ts = datetime.now().strftime("%H:%M")
    
    # Анализируем логи HA watchdog
    try:
        watchdog_log = open("/var/log/argos_ha_watchdog.log", errors="replace").read()
        last_lines = watchdog_log.strip().split("\n")[-5:]
    except:
        last_lines = ["нет лога"]
    
    # Проверяем unavailable entities
    states = ha_api()
    unavail = [s['entity_id'] for s in states if s.get('state') == 'unavailable'] if isinstance(states, list) else []
    
    # Пишем скрипт auto-heal
    if unavail:
        script_content = f"""#!/usr/bin/env python3
# Auto-generated by entity-claude at {ts}
# Auto-heal для {len(unavail)} unavailable entities
import urllib.request, json, re, sys

HA_TOKEN = re.search(r'HA_TOKEN=([^\\n\\s]+)', open('/home/ava/Projects/argoss/.env').read()).group(1)

def ha(method, path, data=None):
    body = json.dumps(data or {{}}).encode() if data else None
    req = urllib.request.Request(f'http://localhost:8123/api{{path}}',
        data=body, headers={{'Authorization': f'Bearer {{HA_TOKEN}}', 'Content-Type': 'application/json'}},
        method=method)
    try:
        with urllib.request.urlopen(req, timeout=5) as r:
            return r.status
    except: return 0

# Перезагружаем интеграции
domains = list(set(e.split('.')[0] for e in {unavail[:5]}))
for domain in domains:
    status = ha('POST', f'/services/{{domain}}/reload')
    print(f'Reload {{domain}}: {{status}}')
"""
        script_path = ARGOS / f"generated/claude_autoheal_{int(time.time())}.py"
        script_path.write_text(script_content)
        
        # Выполняем скрипт
        result = run_cmd(f"/home/ava/Projects/argoss/.venv/bin/python3 {script_path}", timeout=20)
        
        report = f"✅ Клод [{ts}]: написал и выполнил auto-heal\nUnavail: {unavail[:3]}\nРезультат: {result[:150]}"
    else:
        # Нет проблем — пишем новый модуль
        report = f"✅ Клод [{ts}]: все HA entities доступны (0 unavail)\nWatchdog: {last_lines[-1][:80]}"
    
    send_to_group("argos_claude_ai_bot", report)
    write_obsidian("entities/memory/claude.md", report)
    return report

def kimi_task():
    """Кими: мониторит Brain и HA, отправляет реальные алерты."""
    ts = datetime.now().strftime("%H:%M")
    
    brain = brain_api()
    nodes = brain.get("nodes", [])
    online = [n['node_id'] for n in nodes if n.get('status') == 'online']
    offline = [n['node_id'] for n in nodes if n.get('status') != 'online']
    
    # Реальный системный мониторинг
    cpu = run_cmd("top -bn1 | grep 'Cpu(s)' | awk '{print $2}'")
    mem = run_cmd("free -m | grep Mem | awk '{print $3\"/\"$2}'")
    disk = run_cmd("df -h / | tail -1 | awk '{print $5}'")
    
    report = (f"📊 Кими [{ts}] Мониторинг:\n"
              f"Brain: {len(online)}/{len(nodes)} online\n"
              f"CPU: {cpu.strip()[:20]}%  RAM: {mem.strip()[:20]}MB\n"
              f"Disk: {disk.strip()}\n")
    
    if offline:
        report += f"⚠️ Offline: {', '.join(offline[:5])}"
        send_to_group("argos_kimi_ai_bot", report)
    else:
        send_to_group("argos_kimi_ai_bot", report)
    
    write_obsidian("entities/memory/kimi.md", report)
    return report

def deepseek_task():
    """Дипсик: синхронизирует файлы и выполняет реальные команды."""
    ts = datetime.now().strftime("%H:%M")
    
    # Реальные действия: проверяем сервисы и синхронизируем
    services = ["argos-entity-bus", "argos-autopilot", "argos-claude-bridge", "argos-ha-watchdog"]
    status = {}
    for svc in services:
        result = run_cmd(f"systemctl is-active {svc}")
        status[svc] = result.strip()
    
    # Перезапускаем упавшие
    restarted = []
    for svc, st in status.items():
        if st != "active":
            run_cmd(f"sudo systemctl restart {svc}")
            restarted.append(svc)
    
    # Обновляем WORKING.md с реальными данными
    content = (f"=== [{ts}] Дипсик — отчёт ===\n"
               f"Сервисы: {json.dumps(status, ensure_ascii=False)}\n")
    if restarted:
        content += f"Перезапущены: {restarted}\n"
    
    write_obsidian("shared/STATUS.md", content)
    
    report = f"🔄 Дипсик [{ts}]:\n" + "\n".join(f"{'✅' if v=='active' else '❌'} {k}: {v}" for k,v in status.items())
    if restarted:
        report += f"\n🔧 Перезапущено: {', '.join(restarted)}"
    
    send_to_group("argos_deepseek_v3_bot", report)
    return report

def gemini_task():
    """Джемини: генерирует контент и анализирует HA."""
    ts = datetime.now().strftime("%H:%M")
    
    # Анализируем HA entities
    states = ha_api()
    if isinstance(states, list):
        domains = {}
        for s in states:
            d = s['entity_id'].split('.')[0]
            domains[d] = domains.get(d, 0) + 1
        
        top_domains = sorted(domains.items(), key=lambda x: -x[1])[:5]
        unavail = len([s for s in states if s.get('state') == 'unavailable'])
        
        report = (f"📈 Джемини [{ts}] HA Analytics:\n"
                  f"Всего: {len(states)} entities\n"
                  f"Unavailable: {unavail}\n"
                  f"Top domains: {', '.join(f'{k}:{v}' for k,v in top_domains)}\n"
                  f"\nTON стратегия: публикуем ARGOS в Telegram каналах для привлечения пользователей.")
    else:
        report = f"📈 Джемини [{ts}]: HA недоступен, анализ пропущен"
    
    send_to_group("argos_gemini_v3_bot", report)
    write_obsidian("entities/memory/gemini.md", report)
    return report

def openai_task():
    """OpenAI: создаёт реальные API endpoints и тестирует их."""
    ts = datetime.now().strftime("%H:%M")
    
    # Создаём простой API endpoint
    api_code = f'''#!/usr/bin/env python3
# ARGOS Status API — генерирован entity-openai at {ts}
from http.server import HTTPServer, BaseHTTPRequestHandler
import json, urllib.request

class StatusHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        try:
            r = urllib.request.urlopen("http://192.168.1.53:5001/brain/nodes", timeout=3)
            data = json.loads(r.read())
        except:
            data = {{"error": "Brain недоступен"}}
        
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps(data, ensure_ascii=False).encode())
    
    def log_message(self, *args): pass

if __name__ == "__main__":
    server = HTTPServer(("0.0.0.0", 8082), StatusHandler)
    print("ARGOS Status API на :8082")
    server.serve_forever()
'''
    
    script_path = ARGOS / "generated/openai_status_api.py"
    script_path.write_text(api_code)
    
    # Тестируем существующий Brain API
    brain = brain_api()
    online = brain.get('online', 0)
    total = brain.get('total', 0)
    
    report = (f"⚙️ OpenAI [{ts}]:\n"
              f"Создан status API: {script_path.name}\n"
              f"Brain: {online}/{total} нод\n"
              f"Эндпоинты доступны: /brain/nodes, /brain/status")
    
    send_to_group("argos_openai_v3_bot", report)
    write_obsidian("entities/memory/openai.md", report)
    return report

def cloudflare_task():
    """Cloudflare: мониторит туннели и CF Workers."""
    ts = datetime.now().strftime("%H:%M")
    
    # Проверяем реальные CF туннели
    results = {}
    for host, url in [
        ("ha.argosssss.win", "https://ha.argosssss.win/"),
        ("brain-laptop", "https://brain-laptop.argosssss.win/health"),
        ("api-laptop", "https://api-laptop.argosssss.win/"),
    ]:
        try:
            req = urllib.request.Request(url)
            with urllib.request.urlopen(req, timeout=5) as r:
                results[host] = f"{r.status} ✅"
        except urllib.error.HTTPError as e:
            results[host] = f"{e.code} ⚠️"
        except Exception as e:
            results[host] = f"ERR ❌"
    
    # Проверяем cloudflared процесс
    cf_status = run_cmd("systemctl is-active cloudflared")
    
    report = (f"☁️ Клауд [{ts}] CF статус:\n"
              f"cloudflared: {cf_status.strip()}\n"
              + "\n".join(f"{h}: {s}" for h, s in results.items()))
    
    send_to_group("argos_cloudflare_bot", report)
    write_obsidian("entities/memory/cloudflare.md", report)
    return report

# ── ГЛАВНЫЙ ЦИКЛ ──────────────────────────────────────────────────────

ENTITY_TASKS = {
    "claude": claude_task,
    "kimi": kimi_task,
    "deepseek": deepseek_task,
    "gemini": gemini_task,
    "openai": openai_task,
    "cloudflare": cloudflare_task,
}

def main():
    print(f"Entity Task Runner запущен | интервал {INTERVAL}с")
    
    cycle = 0
    while True:
        cycle += 1
        ts = datetime.now().strftime("%H:%M:%S")
        print(f"\n[{ts}] Цикл #{cycle}")
        
        for entity, task_fn in ENTITY_TASKS.items():
            try:
                result = task_fn()
                print(f"  ✅ {entity}: {result[:80]}")
            except Exception as e:
                print(f"  ❌ {entity}: {e}")
        
        time.sleep(INTERVAL)

if __name__ == "__main__":
    main()
